/* Generated By:JavaCC: Do not edit this line. CParserConstants.java */
package com.idofast.admin.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 13;
  /** RegularExpression Id. */
  int HEX_LITERAL = 14;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 15;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 16;
  /** RegularExpression Id. */
  int EXPONENT = 17;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 18;
  /** RegularExpression Id. */
  int STRING_LITERAL = 19;
  /** RegularExpression Id. */
  int LEFT_BRACE = 20;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int FEN_HAO = 24;
  /** RegularExpression Id. */
  int LEFT_MIDDLE_BRACKET = 25;
  /** RegularExpression Id. */
  int RIGHT_MIDDLE_BRACKET = 26;
  /** RegularExpression Id. */
  int LEFT_SMALL_BRACKET = 27;
  /** RegularExpression Id. */
  int RIGHT_SMALL_BRACKET = 28;
  /** RegularExpression Id. */
  int COMMA = 29;
  /** RegularExpression Id. */
  int ARROW = 30;
  /** RegularExpression Id. */
  int ADD = 31;
  /** RegularExpression Id. */
  int DIVIDE = 32;
  /** RegularExpression Id. */
  int MULTIPLE = 33;
  /** RegularExpression Id. */
  int DIVISION = 34;
  /** RegularExpression Id. */
  int EQUAL = 35;
  /** RegularExpression Id. */
  int EMPTY = 36;
  /** RegularExpression Id. */
  int CONTINUE = 37;
  /** RegularExpression Id. */
  int VOLATILE = 38;
  /** RegularExpression Id. */
  int REGISTER = 39;
  /** RegularExpression Id. */
  int UNSIGNED = 40;
  /** RegularExpression Id. */
  int TYPEDEF = 41;
  /** RegularExpression Id. */
  int DFLT = 42;
  /** RegularExpression Id. */
  int DOUBLE = 43;
  /** RegularExpression Id. */
  int SIZEOF = 44;
  /** RegularExpression Id. */
  int SWITCH = 45;
  /** RegularExpression Id. */
  int RETURN = 46;
  /** RegularExpression Id. */
  int EXTERN = 47;
  /** RegularExpression Id. */
  int STRUCT = 48;
  /** RegularExpression Id. */
  int STATIC = 49;
  /** RegularExpression Id. */
  int SIGNED = 50;
  /** RegularExpression Id. */
  int WHILE = 51;
  /** RegularExpression Id. */
  int BREAK = 52;
  /** RegularExpression Id. */
  int UNION = 53;
  /** RegularExpression Id. */
  int CONST = 54;
  /** RegularExpression Id. */
  int FLOAT = 55;
  /** RegularExpression Id. */
  int SHORT = 56;
  /** RegularExpression Id. */
  int ELSE = 57;
  /** RegularExpression Id. */
  int CASE = 58;
  /** RegularExpression Id. */
  int LONG = 59;
  /** RegularExpression Id. */
  int ENUM = 60;
  /** RegularExpression Id. */
  int AUTO = 61;
  /** RegularExpression Id. */
  int VOID = 62;
  /** RegularExpression Id. */
  int CHAR = 63;
  /** RegularExpression Id. */
  int GOTO = 64;
  /** RegularExpression Id. */
  int FOR = 65;
  /** RegularExpression Id. */
  int INT = 66;
  /** RegularExpression Id. */
  int IF = 67;
  /** RegularExpression Id. */
  int DO = 68;
  /** RegularExpression Id. */
  int IDENTIFIER = 69;
  /** RegularExpression Id. */
  int LETTER = 70;
  /** RegularExpression Id. */
  int DIGIT = 71;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"#\"",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 11>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"&\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"->\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"\\u03b5\"",
    "\"continue\"",
    "\"volatile\"",
    "\"register\"",
    "\"unsigned\"",
    "\"typedef\"",
    "\"default\"",
    "\"double\"",
    "\"sizeof\"",
    "\"switch\"",
    "\"return\"",
    "\"extern\"",
    "\"struct\"",
    "\"static\"",
    "\"signed\"",
    "\"while\"",
    "\"break\"",
    "\"union\"",
    "\"const\"",
    "\"float\"",
    "\"short\"",
    "\"else\"",
    "\"case\"",
    "\"long\"",
    "\"enum\"",
    "\"auto\"",
    "\"void\"",
    "\"char\"",
    "\"goto\"",
    "\"for\"",
    "\"int\"",
    "\"if\"",
    "\"do\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
