/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package cn.edu.nwafu.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int SHORT = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int LONG = 16;
  /** RegularExpression Id. */
  int FLOAT = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int STRUCT = 19;
  /** RegularExpression Id. */
  int UNION = 20;
  /** RegularExpression Id. */
  int ENUM = 21;
  /** RegularExpression Id. */
  int STATIC = 22;
  /** RegularExpression Id. */
  int EXTERN = 23;
  /** RegularExpression Id. */
  int CONST = 24;
  /** RegularExpression Id. */
  int SIGNED = 25;
  /** RegularExpression Id. */
  int UNSIGNED = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int SWITCH = 29;
  /** RegularExpression Id. */
  int CASE = 30;
  /** RegularExpression Id. */
  int DEFAULT_ = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int DO = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int RETURN = 35;
  /** RegularExpression Id. */
  int BREAK = 36;
  /** RegularExpression Id. */
  int CONTINUE = 37;
  /** RegularExpression Id. */
  int GOTO = 38;
  /** RegularExpression Id. */
  int TYPEDEF = 39;
  /** RegularExpression Id. */
  int IMPORT = 40;
  /** RegularExpression Id. */
  int SIZEOF = 41;
  /** RegularExpression Id. */
  int OMIT = 42;
  /** RegularExpression Id. */
  int EXCAT_PARAM_NAME = 43;
  /** RegularExpression Id. */
  int FORBIDDEN = 44;
  /** RegularExpression Id. */
  int IDENTIFIER = 45;
  /** RegularExpression Id. */
  int INTEGER = 46;
  /** RegularExpression Id. */
  int CHARACTER = 47;
  /** RegularExpression Id. */
  int STRING = 48;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 49;
  /** RegularExpression Id. */
  int EXPONENT = 50;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"#\"",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 11>",
    "\"void\"",
    "\"char\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"struct\"",
    "\"union\"",
    "\"enum\"",
    "\"static\"",
    "\"extern\"",
    "\"const\"",
    "\"signed\"",
    "\"unsigned\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"goto\"",
    "\"typedef\"",
    "\"import\"",
    "\"sizeof\"",
    "\"---\"",
    "\"<EXACT_PARAM_NAME>\"",
    "\"<forbidden>\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<CHARACTER>",
    "<STRING>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\"(\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\")\"",
    "\"...\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"[\"",
    "\"]\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"~\"",
    "\".\"",
    "\"->\"",
  };

}
