server:
  port: 8001

spring:
  datasource:
    username: root
    password: idofast
    url: jdbc:mysql:///oj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host:
    username:
    password:
    properties.mail.smtp.port: 465 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  profiles:
    active: local

email:
  username: z
  senderName: C语言在线编译器



token:
  secret: nwafu
  # 单位 分钟
  expiration: 43200

#是否真的发送email；方便测试
switch:
  sendEmail: true



compiler:
  userFolder: /Users/zhaomanzhou/IdeaProjects/GrammerCompiler/afile/user/
  problemFolder: /Users/zhaomanzhou/IdeaProjects/GrammerCompiler/afile/admin/



mq:
  nameserver:
    addr: 127.0.0.1:9876
  topicname: codeJudge

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace




